services:
  mongodb:
    image: mongo:7-jammy            # Docker image name and tag to run 
    container_name: mongodb         # Explicit container name
    ports:
      - "27007:27017"               # HostPort:ContainerPort — expose Mongo on host port 27007
    volumes:
      - mongodatabase:/data/db          # HostDir:ContainerDir — persist DB files on host
    networks:
      - backend
    restart: always                  # Always restart container on failure/reboot

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  pgvector:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    container_name: pgvector
    ports:
      - "5400:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - backend
    restart: always


networks:
  backend:                           # User-defined network for service-to-service communication

volumes:
  mongodatabase:                     # Named volume for MongoDB data persistence
  pgvector_data:                     # Named volume for PostgreSQL data persistence